# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba584173e3a016e7b37ffc9e433cb4b3b5b4d70fb981caf56ab938315eed33c14b9d2012ee920cecdf4358f0b17a46f7a3371fd00758a43e2c405af87cff10ba

test:
  secret_key_base: adceea940343838f606fa3e4072c809e9b6ddb7cefc8bf0395d0cefc88a85a3276af3f73c3f0cac6943ba7534e6acf6577f549da64b2ebb4b41df1be7c644d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
